task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 10 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/mxs/datasets/visdrone/VisDrone2019-DET-train/images
    ann_file: /home/mxs/datasets/visdrone/VisDrone2019-DET-train/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 0
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/mxs/datasets/visdrone/VisDrone2019-DET-val/images
    ann_file: /home/mxs/datasets/visdrone/VisDrone2019-DET-val/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: 
        - {type: Resize, size: [640, 640], }
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
  shuffle: False
  num_workers: 2
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction

test_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/mxs/datasets/visdrone/VisDrone2019-DET-test-dev/images
    ann_file: /home/mxs/datasets/visdrone/VisDrone2019-DET-test-dev/test.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 2
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction
